# Generated by Django 4.2.1 on 2023-06-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signins', '0005_alter_twofa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofa',
            name='user',
        ),
        migrations.DeleteModel(
            name='BackupCode',
        ),
        migrations.DeleteModel(
            name='TwoFA',
        ),
    ]
