# Generated by Django 4.2.1 on 2023-06-07 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('signins', '0006_remove_twofa_user_delete_backupcode_delete_twofa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFA',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('twofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signins.twofa')),
            ],
        ),
    ]
